# Generated by Django 6.0.4 on 2026-04-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
    ]
